### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by leonardoballand**
**VirtualKeyboard updates**

- add testID prop to popup error container
- add testID prop to text inside popup error
- add testID prop to disabled key

**Documentation**
- new props are now documented

**Package**
- Bump version package (seems to be different of last release tag)

### CODE REVIEW

**Comment by lukebrandonfarrell** [comment]
LGTM!

**Comment by lukebrandonfarrell** [comment]
@all-contributors add @leonardoballand for code and docs

**Comment by lukebrandonfarrell** [comment]
@leonardoballand this will go to NPM on the next PR as the PR title was merged without a fix() or feat() prefix so it was skipped in the release process.

**Comment by leonardoballand** [comment]
> @all-contributors add @leonardoballand for code and docs

Ahah no luck with this but thanks! ☺️

**Comment by lukebrandonfarrell** [comment]
@leonardoballand We will get it working again :D lol

**Comment by lukebrandonfarrell** [comment]
@all-contributors add @leonardoballand for code and docs

**Pull request merged**
